### PR TITLE
Fixed country/state/city selection

### PR DESCRIPTION
**Pull request by vibalcam**
`cucumber features/sign_in_up.feature` should be working again

### CODE REVIEW

**Comment by AJ1904** [comment]
The tests dont pass
image

On trying to edit profile manually, city dropdown doesn't populate.
image

**Comment by AJ1904** [comment]
Cache is cleared, running in incognito mode.
Ran these rake assets:clobber and rake assets:precompile but tests don't pass.
image

**Comment by vibalcam** [comment]
Are you running locally?
If so, I'm test.rb, use remote web driver should be false.

It looks like the error you are getting is running cucumber, no the test.

**Comment by AJ1904** [comment]
Yes, running locally.

**Comment by AJ1904** [comment]
Thanks, I updated test.rb and tests pass.
One question, city is not a dropdown now, it is a text field?

**Comment by vibalcam** [comment]
Yes, I've changed it.
Getting the countries etc is not as straightforward as it might seem since there are many countries that it's not so sure whether they should be called some way or even if it is a country.

One way is using a 3rd party, which it's what they where doing and broke. I found other options but they required API keys, which I felt like added even more complexity.

So what I did is to download locally a list of them.
For the cities, there are too many of them and even small ones that might not be available, which is why I chose to use a text box

**Comment by vibalcam** [comment]
Either way, if you want to add more precision to the search, you should not use cities as measure. Instead you should ask for the postal code (which is well defined and you can use to retrieve the location)

We can bring up this to Tito today.

**Review by AJ1904 — APPROVED** [review]
Approved.
Inform client that city is a text box now.

**Pull request merged**
